###################################################################

# Created by write_sdc on Fri Feb 13 10:28:55 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_capacitance 0.2 [current_design]
set_max_transition 1.5 [current_design]
set_load -pin_load 0.02 [get_ports {p_out[31]}]
set_load -pin_load 0.02 [get_ports {p_out[30]}]
set_load -pin_load 0.02 [get_ports {p_out[29]}]
set_load -pin_load 0.02 [get_ports {p_out[28]}]
set_load -pin_load 0.02 [get_ports {p_out[27]}]
set_load -pin_load 0.02 [get_ports {p_out[26]}]
set_load -pin_load 0.02 [get_ports {p_out[25]}]
set_load -pin_load 0.02 [get_ports {p_out[24]}]
set_load -pin_load 0.02 [get_ports {p_out[23]}]
set_load -pin_load 0.02 [get_ports {p_out[22]}]
set_load -pin_load 0.02 [get_ports {p_out[21]}]
set_load -pin_load 0.02 [get_ports {p_out[20]}]
set_load -pin_load 0.02 [get_ports {p_out[19]}]
set_load -pin_load 0.02 [get_ports {p_out[18]}]
set_load -pin_load 0.02 [get_ports {p_out[17]}]
set_load -pin_load 0.02 [get_ports {p_out[16]}]
set_load -pin_load 0.02 [get_ports {p_out[15]}]
set_load -pin_load 0.02 [get_ports {p_out[14]}]
set_load -pin_load 0.02 [get_ports {p_out[13]}]
set_load -pin_load 0.02 [get_ports {p_out[12]}]
set_load -pin_load 0.02 [get_ports {p_out[11]}]
set_load -pin_load 0.02 [get_ports {p_out[10]}]
set_load -pin_load 0.02 [get_ports {p_out[9]}]
set_load -pin_load 0.02 [get_ports {p_out[8]}]
set_load -pin_load 0.02 [get_ports {p_out[7]}]
set_load -pin_load 0.02 [get_ports {p_out[6]}]
set_load -pin_load 0.02 [get_ports {p_out[5]}]
set_load -pin_load 0.02 [get_ports {p_out[4]}]
set_load -pin_load 0.02 [get_ports {p_out[3]}]
set_load -pin_load 0.02 [get_ports {p_out[2]}]
set_load -pin_load 0.02 [get_ports {p_out[1]}]
set_load -pin_load 0.02 [get_ports {p_out[0]}]
set_load -pin_load 0.02 [get_ports done]
set_max_fanout 1 [get_ports clk]
set_max_fanout 1 [get_ports rst_n]
set_max_fanout 1 [get_ports start]
set_max_fanout 1 [get_ports {a_in[15]}]
set_max_fanout 1 [get_ports {a_in[14]}]
set_max_fanout 1 [get_ports {a_in[13]}]
set_max_fanout 1 [get_ports {a_in[12]}]
set_max_fanout 1 [get_ports {a_in[11]}]
set_max_fanout 1 [get_ports {a_in[10]}]
set_max_fanout 1 [get_ports {a_in[9]}]
set_max_fanout 1 [get_ports {a_in[8]}]
set_max_fanout 1 [get_ports {a_in[7]}]
set_max_fanout 1 [get_ports {a_in[6]}]
set_max_fanout 1 [get_ports {a_in[5]}]
set_max_fanout 1 [get_ports {a_in[4]}]
set_max_fanout 1 [get_ports {a_in[3]}]
set_max_fanout 1 [get_ports {a_in[2]}]
set_max_fanout 1 [get_ports {a_in[1]}]
set_max_fanout 1 [get_ports {a_in[0]}]
set_max_fanout 1 [get_ports {b_in[15]}]
set_max_fanout 1 [get_ports {b_in[14]}]
set_max_fanout 1 [get_ports {b_in[13]}]
set_max_fanout 1 [get_ports {b_in[12]}]
set_max_fanout 1 [get_ports {b_in[11]}]
set_max_fanout 1 [get_ports {b_in[10]}]
set_max_fanout 1 [get_ports {b_in[9]}]
set_max_fanout 1 [get_ports {b_in[8]}]
set_max_fanout 1 [get_ports {b_in[7]}]
set_max_fanout 1 [get_ports {b_in[6]}]
set_max_fanout 1 [get_ports {b_in[5]}]
set_max_fanout 1 [get_ports {b_in[4]}]
set_max_fanout 1 [get_ports {b_in[3]}]
set_max_fanout 1 [get_ports {b_in[2]}]
set_max_fanout 1 [get_ports {b_in[1]}]
set_max_fanout 1 [get_ports {b_in[0]}]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty -setup 1.2  [get_clocks clk]
set_clock_uncertainty -hold 1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.12 [get_clocks clk]
set_clock_transition -min -fall 0.12 [get_clocks clk]
create_clock -name v_clk  -period 10  -waveform {0 5}
set_input_delay -clock v_clk  3  [get_ports rst_n]
set_input_delay -clock v_clk  3  [get_ports start]
set_input_delay -clock v_clk  3  [get_ports {a_in[15]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[14]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[13]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[12]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[11]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[10]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[9]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[8]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[7]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[6]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[5]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[4]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[3]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[2]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[1]}]
set_input_delay -clock v_clk  3  [get_ports {a_in[0]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[15]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[14]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[13]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[12]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[11]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[10]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[9]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[8]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[7]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[6]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[5]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[4]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[3]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[2]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[1]}]
set_input_delay -clock v_clk  3  [get_ports {b_in[0]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[31]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[30]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[29]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[28]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[27]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[26]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[25]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[24]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[23]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[22]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[21]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[20]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[19]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[18]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[17]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[16]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[15]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[14]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[13]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[12]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[11]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[10]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[9]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[8]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[7]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[6]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[5]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[4]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[3]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[2]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[1]}]
set_output_delay -clock v_clk  3  [get_ports {p_out[0]}]
set_output_delay -clock v_clk  3  [get_ports done]
set_input_transition -max -rise 0.1  [get_ports clk]
set_input_transition -max -fall 0.12  [get_ports clk]
set_input_transition -min -rise 0.1  [get_ports clk]
set_input_transition -min -fall 0.12  [get_ports clk]
set_input_transition -max -rise 0.1  [get_ports rst_n]
set_input_transition -max -fall 0.12  [get_ports rst_n]
set_input_transition -min -rise 0.1  [get_ports rst_n]
set_input_transition -min -fall 0.12  [get_ports rst_n]
set_input_transition -max -rise 0.1  [get_ports start]
set_input_transition -max -fall 0.12  [get_ports start]
set_input_transition -min -rise 0.1  [get_ports start]
set_input_transition -min -fall 0.12  [get_ports start]
set_input_transition -max -rise 0.1  [get_ports {a_in[15]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[15]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[15]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[15]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[14]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[14]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[14]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[14]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[13]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[13]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[13]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[13]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[12]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[12]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[12]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[12]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[11]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[11]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[11]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[11]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[10]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[10]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[10]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[10]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[9]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[9]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[9]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[9]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[8]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[8]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[8]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[8]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[7]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[7]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[7]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[7]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[6]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[6]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[6]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[6]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[5]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[5]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[5]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[5]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[4]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[4]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[4]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[4]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[3]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[3]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[3]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[3]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[2]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[2]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[2]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[2]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[1]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[1]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[1]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[1]}]
set_input_transition -max -rise 0.1  [get_ports {a_in[0]}]
set_input_transition -max -fall 0.12  [get_ports {a_in[0]}]
set_input_transition -min -rise 0.1  [get_ports {a_in[0]}]
set_input_transition -min -fall 0.12  [get_ports {a_in[0]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[15]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[15]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[15]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[15]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[14]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[14]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[14]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[14]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[13]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[13]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[13]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[13]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[12]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[12]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[12]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[12]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[11]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[11]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[11]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[11]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[10]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[10]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[10]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[10]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[9]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[9]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[9]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[9]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[8]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[8]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[8]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[8]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[7]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[7]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[7]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[7]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[6]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[6]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[6]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[6]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[5]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[5]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[5]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[5]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[4]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[4]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[4]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[4]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[3]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[3]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[3]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[3]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[2]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[2]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[2]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[2]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[1]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[1]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[1]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[1]}]
set_input_transition -max -rise 0.1  [get_ports {b_in[0]}]
set_input_transition -max -fall 0.12  [get_ports {b_in[0]}]
set_input_transition -min -rise 0.1  [get_ports {b_in[0]}]
set_input_transition -min -fall 0.12  [get_ports {b_in[0]}]
